version: '3.8'
services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - cache:/data

  backend:
    build: ./apps/background
    ports:
      - '3001:3001'
    depends_on: 
      - redis

  frontend:
    build: ./apps/frontend
    ports:
      - '3000:3000'
    depends_on: 
      - backend

volumes:
  cache:
    driver: local