apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stripe-backend
    app.kubernetes.io/managed-by: Helm
  name: stripe-backend
spec:
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: stripe-backend
