apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stripe-frontend
    app.kubernetes.io/managed-by: Helm
  name: stripe-frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: stripe-frontend
