apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stripe-backend
    app.kubernetes.io/managed-by: Helm
  name: stripe-backend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: stripe-backend
  type: NodePort
status:
  loadBalancer: {}
